swagger: "2.0"
info:
  description: "This describes how to talk to the Battle Dev Severus. Be nice with him."
  version: "1.0.0"
  title: "Battle Dev Severus"
  contact:
    email: "8.bachrc@gmail.com"
  license:
    name: "WTFPL"
    url: "http://www.wtfpl.net/about/"
basePath: "/"
tags:
  - name: "problems"
    description: "Everything related to problems"
  - name: "authentication"
    description: "Related to authentication to the app"
schemes:
  - "https"
  - "http"
paths:
  /problems:
    get:
      tags:
        - "problems"
      summary: "Returns every problem summary"
      description: "Returns every problems summary in the database"
      operationId: "getProblems"
      produces:
        - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/ProblemsList'

definitions:
  ProblemsList:
    type: array
    items:
      $ref: '#/definitions/ProblemSummary'

  ProblemSummary:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
