openapi: "3.0"
info:
  description: "This describes how to talk to the Battle Dev Severus. Be nice with him."
  version: "1.0.0"
  title: "Battle Dev Severus"
  contact:
    email: "8.bachrc@gmail.com"
  license:
    name: "WTFPL"
    url: "http://www.wtfpl.net/about/"

tags:
  - name: "problems"
    description: "Everything related to problems"
  - name: "authentication"
    description: "Related to authentication to the app"

paths:
  /problems:
    get:
      tags:
        - "problems"
      summary: "Returns every problem summary"
      operationId: "getProblems"
      parameters: []
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProblemSummary'

  /problems/{problemId}:
    get:
      tags:
        - "problems"
      summary: "Returns problem detail"
      operationId: "getProblemById"
      parameters:
        - name: "problemId"
          in: "path"
          description: "ID of the problem to fetch"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Problem not found"

components:
  schemas:
    ProblemSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
    Problem:
      allOf:
        - $ref: '#/components/schemas/ProblemSummary'
        - type: object
          properties:
            contenu:
              type: string
            question:
              type: string
