# Generated by Django 2.2.3 on 2019-08-14 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('reponse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.CharField(max_length=10000)),
                ('index', models.IntegerField(unique=True)),
                ('questions', models.ManyToManyField(blank=True, to='lobby.Question')),
            ],
        ),
        migrations.CreateModel(
            name='BonneReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now=True)),
                ('probleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.Probleme')),
                ('utilisateur',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
