# Generated by Django 2.2.3 on 2019-07-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='titre',
            field=models.CharField(default='Dessert', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='probleme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
