# Generated by Django 2.2.3 on 2019-08-15 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MauvaiseReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_donnee', models.CharField(max_length=1000)),
                ('date_soumission', models.DateTimeField(auto_now=True)),
                ('probleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.Probleme')),
                ('utilisateur',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
