# Generated by Django 2.2.3 on 2019-08-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lobby', '0002_mauvaisereponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
            ],
        ),
    ]
